CREATE DATABASE SOMATIVA_MYSQL;
CREATE DATABASE SOMATIVA;
USE SOMATIVA_MYSQL;

CREATE TABLE IF NOT EXISTS CLIENTES (
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLIENTE VARCHAR(30) NOT NULL,
TELEFONE_CLIENTE VARCHAR(15) NOT NULL UNIQUE,
DATA_NASCIMENTO DATE NOT NULL,
POSSUI_CADASTRO ENUM('SIM,NAO') NOT NULL,
EMAIL_CLIENTE VARCHAR(30) NOT NULL
);


CREATE TABLE IF NOT EXISTS VEÍCULOS(
PESO_VEICULO INT NOT NULL,
ANO_FABRICAÇÃO_VEICULO DATE NOT NULL,
DOCUMENTAÇAO_VEICULO VARCHAR(30) NOT NULL,
TIPO_DE_VEICULO VARCHAR(30) NOT NULL,
PLACA_VEICULO VARCHAR(15) NOT NULL,
ID_VEICULO INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS MARCAS(
MARCA_RECENTE VARCHAR(30) NOT NULL,
ID_MARCA  INT AUTO_INCREMENT PRIMARY KEY,
NACIONALIDADE_MARCA VARCHAR(15) NOT NULL,
NOME_MARCA VARCHAR(30) NOT NULL,
MARCA_ANTIGA VARCHAR(30) NOT NULL,
ANO_FABRICAÇÃO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS MODELOS(
MODELO ENUM('NOVO,ANTIGO') NOT NULL,
PEÇAS_SERÃO_TROCADAS VARCHAR(30) NOT NULL,
NOME_MARCA VARCHAR(30) NOT NULL,
COR_MODELO VARCHAR(10) NOT NULL,
NOME_MODELO VARCHAR(30) NOT NULL,
ID_MODELO  INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
DATA_ENTRADA_EMPRESA INT NOT NULL,
IDADE_FUNCIONARIOS INT NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
ID_FUNCIONARIO  INT AUTO_INCREMENT PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR(30) NOT NULL,
CPF_FUNCONARIO VARCHAR(14) NOT NULL UNIQUE 
);

CREATE TABLE IF NOT EXISTS SERVIÇOS(
NOME_DE_CADA_SERVIÇO VARCHAR(15) NOT NULL ,
CARGOS VARCHAR(15) NOT NULL,
TURNOS VARCHAR(10) NOT NULL,
SALARIO_INICIAL_CADA_SERVIÇO INT NOT NULL,
QUANTIDADE_FUNCIONARIOS_EM_CADA_SERVIÇO INT NOT NULL,
ID_SERVIÇOS INT AUTO_INCREMENT PRIMARY KEY,
HORARIO_DE_PAUSA_CADA_SERVIÇO TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS PEÇAS(
IMPORTAÇÃO ENUM('INTERNACIONAL,NACIONAL') NOT NULL,
TAMANHO_PEÇA INT NOT NULL,
PREÇO_CLIENTE INT NOT NULL,
ID_PEÇA INT AUTO_INCREMENT PRIMARY KEY,
NOME_PEÇA VARCHAR(20) NOT NULL,
PREÇO_PARA_EMPRESA INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDEM_DE_SERVIÇOS(
NOME_REPONSAVEL INT NOT NULL,
DESCRIÇÃO VARCHAR(30) NOT NULL,
VALOR_TOTAL INT NOT NULL,
DATA_FECHAMENTO DATE NOT NULL,
DATA_ABERTURA DATE NOT NULL,
ID_SERVIÇOS INT AUTO_INCREMENT PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS PAGAMENTOS(
VALOR_PAGAMENTO INT NOT NULL,
DATA_PAGAMENTO DATE NOT NULL,
PAGAMENTO_REALIZADO  ENUM('NÃO,SIM') NOT NULL,
PARCELAMENTO ENUM('NÃO,SIM') NOT NULL,
CPF VARCHAR(14) NOT NULL,
ID_PAGAMENTOS INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
DATA_DE_CADA_ENTREGA DATE NOT NULL,
EMAIL VARCHAR(50)NOT NULL,
CNPJ INT NOT NULL,
NOME_ENTREGADOR VARCHAR(30) NOT NULL,
NOME_FORNECEDOR VARCHAR(30) NOT NULL
);


SHOW TABLES;

SHOW DATABASES;

ALTER TABLE VEÍCULOS ADD LOCAL_FABRICACAO VARCHAR(100) NOT NULL;
ALTER TABLE  VEÍCULOS DROP COLUMN LOCAL_FABRICADO;

ALTER TABLE MARCAS ADD LOCAL_ORIGEM VARCHAR(100) NOT NULL;
ALTER TABLE MARCAR DROP COLUMN LOCAL_ORIGEM;

ALTER TABLE MODELOS ADD PREÇO DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE MODELOS DROP COLUMN PRECO;

ALTER TABLE FUNCIONARIOS ADD EMAIL VARCHAR(100);
ALTER TABLE MODELOS DROP COLUMN EMAIL;





RENAME  TABLE MODELOS TO MODELOS_FAB;



















