CREATE DATABASE IF NOT EXISTS SESI_EXTECNSAOVSTA;
USE SESI_EXTENSAOVSTA;

SHOW TABLES;


SHOW SCHEMAS;



CREATE TABLE IF NOT EXISTS ALUNOS(
    ID_ALUNOS INT AUTO_INCREMENT PRIMARY KEY,
    NOME_ALUNO VARCHAR(60) NOT NULL,
    CPF_ALUNO VARCHAR(14) NOT NULL,
    data_nascimento DATE NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);




DESCRIBE ALUNOS;