CREATE DATABASE SMARTCOFEE_SISTEMA;
CREATE DATABASE IF NOT EXISTS SMARTCOFFEE_SISTEMA_ISABELLA;
CREATE DATABASE BANCO_DADOS;

CREATE TABLE IF NOT EXISTS CLIENTES (
TELEFONE INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR(60) NOT NULL,
EMAIL VARCHAR(14) NOT NULL UNIQUE,
NOME DATE NOT NULL,
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY

