-- PROJETO SMARTCOFFEE ISABELLA

-- CRIAR BANCO DE DADOS 
-- ATIVAR BANCO DE DADOS 
-- CRIAR TABELAS 

-- OPCIONAIS NO DIA 21/08/2026
-- INSERIR DADOS 
-- CONSULTAR DADOS 


CREATE DATABASE PROJETO_SMARTCOFFEE_ISABELLA;
USE PROJETO_SMARTCOFFEE_ISABELLA;

 CREATE TABLE IF NOT EXISTS CLIENTES (
 ID_CLIENTE INT PRIMARY KEY,
 NOME VARCHAR(20) NOT NULL,
 CPF VARCHAR(14) NOT NULL UNIQUE,
 TELEFONE VARCHAR(15),
 EMAIL VARCHAR(40) NOT NULL
 );
 
 CREATE TABLE IF NOT EXISTS PRODUTOS (
 ID_PRODUTO INT PRIMARY KEY,
 TIPO_PRODUTO VARCHAR(20) NOT NULL,
 VALOR INT NOT NULL,
 VENCIMENTO DATE NOT NULL,
 QUANTIDADE INT NOT NULL
 );
 
  CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
 ID_FUNCIONARIO INT PRIMARY KEY,
 NOME VARCHAR(20) NOT NULL,
 SETOR INT NOT NULL,
 SALARIO DATE NOT NULL,
 CARGO INT NOT NULL
 );
 

 

