-- COMANDOS PARA CRIAR BD-- 
-- PASSO 01
-- cria a pasta 	
CREATE DATABASE CLINICA_MEDICA_ISABELLA;
CREATE DATABASE BANCO_DADOS;
-- @/

-- cria porem da um aviso que ja existe  
CREATE DATABASE IF NOT EXISTS CLINICA_MEDICA_ISABELLA;


-- ATIVAR DB E ATUALIZAR ESQUEMA "SCHEMAS" 
-- 2
USE CLINICA_MEDICA_ISABELLA;

-- CRIAR TABELAS

CREATE TABLE IF NOT EXISTS PACIENTES (
ID_PACIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME_PACIENTE VARCHAR(60) NOT NULL,
CPF VARCHAR(14)  NOT NULL UNIQUE,
DATA_NASCIMENTO DATE NOT NULL,
EMAIL VARCHAR(100) ,
TELEFONE VARCHAR(15),
CONVENIO ENUM('SIM','NÃO') NOT NULL 
 );
 
 CREATE TABLE IF NOT EXISTS PACIENTES02 (
ID_PACIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME_PACIENTE VARCHAR(60) NOT NULL,
CPF VARCHAR(14)  NOT NULL UNIQUE,
DATA_NASCIMENTO DATE NOT NULL,
EMAIL VARCHAR(100) ,
TELEFONE VARCHAR(15),
CONVENIO ENUM('SIM','NÃO') NOT NULL 
 );
 
 
 
 
 
 
 CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
 ID_FUNCIONARIOS INT PRIMARY KEY,
 NOME_FUNCIONARIO VARCHAR(60) NOT NULL,
 CPF VARCHAR(14) NOT NULL UNIQUE,
 TELEFONE VARCHAR(15),
 SALARIO DECIMAL(5,2) DEFAULT 0.00
 );
 
-- ALTERA INFORMAÇOES DA TABELA -- 
-- ALTER TABLE 
-- ADCIONAR UM CAMPO (ATRIBUTO) OU COLUNA NA TABELA 
ALTER TABLE FUNCIONARIOS ADD EMAIL VARCHAR(100) NOT NULL;

-- ALTERAR TIPO DE DADOS DE CAMPO (ATRIBUTO) OU COLUNA NA TABELA
ALTER TABLE FUNCIONARIOS MODIFY EMAIL VARCHAR(50) NOT NULL;

-- APARGAR O CAMPO (ATRIBUTO) OU COLUNA NA TABELA 
ALTER TABLE FUNCIONARIOS DROP COLUMN EMAIL;

-- RENOMEAR TABELAS 
RENAME TABLE FUNCIONARIOS  TO FUNCIONARIOSS;


-- APAGAR DADOS DA TABELA 

TRUNCATE TABLE PACIENTES;
TRUNCATE TABLE PACIENTES02;




-- USARRRRRR COMMMMM RESPONSABILIDADEEEEEEEEEEEEEEEEEEEEE
-- APAGAR BD
DROP DATABASE CLINICA_MEDICA_ISABELLA;
-- ....................................................................
-- APAGAR TABELAS

DROP TABLES FUNCIONARIOS;


-- MOSTRAR  TABELAS NO BD 

SHOW TABLES;

-- MOSTRAR TODOS OS BD 

SHOW TABLES;

-- ----------------------------------------------------------------------

-- INSERIR DADOS NO BD 

INSERT INTO FUNCIONARIOSS(ID_FUNCIONARIOS,CPF,TELEFONE,SALARIO,NOME_FUNCIONARIO)
VALUES (2,'123.456.789-11','(19)23452-5676', '200', 'ISABELLA');

INSERT INTO PACIENTES (ID_PACIENTE,NOME_PACIENTE,CPF,DATA_NASCIMENTO,EMAIL,TELEFONE,CONVENIO)
VALUES (DEFAULT, 'ISABELLA', '123 456 789 78', '1983-10-23' , 'isabella@senai', '(19)23452-4676','SIM');

INSERT INTO PACIENTES02 (ID_PACIENTE,NOME_PACIENTE,CPF,DATA_NASCIMENTO,EMAIL,TELEFONE,CONVENIO)
VALUES (DEFAULT, 'CLAUDEMIR', '123 656 989 77', '2010-02-23' , 'claudemir@senai', '(19)45452-4876','SIM');

-- PADRAO PARA DATA ANO-MES-DIA


-- CONSUTAR DADO BD

SELECT * FROM PACIENTES,PACIENTES02


